channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==8.4.11
  - curl
  - pip
  - pip:
    - jsonschema>=4.18.0a1
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
    - -e .